/** Deterministic dev UUIDs so re-seeding is idempotent and maps to frontend image assets. */
export function userUuid(key: number) {
  return `00000000-0000-4000-b000-${String(key).padStart(12, '0')}`;
}

export function listingUuid(slug: string) {
  const n = Number(slug.replace(/^l/, ''));
  return `00000000-0000-4000-a000-${String(n).padStart(12, '0')}`;
}

export function liveUuid(key: number) {
  return `00000000-0000-4000-c000-${String(key).padStart(12, '0')}`;
}

export const DEFAULT_SHIPPING = 'Buyer pays shipping · 3–5 days within Nigeria';

export type SeedUser = {
  key: number;
  username: string;
  email: string;
  name: string;
  dob?: string;
  bio?: string;
  location?: string;
  setupComplete?: boolean;
  canHostLive?: boolean;
};

export const SEED_USERS: SeedUser[] = [
  {
    key: 1,
    username: 'ada.thrifts',
    email: 'ada.thrifts@throve.dev',
    name: 'Ada Nwosu',
    dob: '12/03/1994',
    bio: 'Curating pre-loved fashion finds. Fast shipping, honest condition notes.',
    location: 'Lagos, NG',
    setupComplete: true,
    canHostLive: true,
  },
  {
    key: 2,
    username: 'sneakerspot.ng',
    email: 'sneakerspot.ng@throve.dev',
    name: 'Tobi Sneakers',
    bio: 'Authenticated sneakers and streetwear drops.',
    location: 'Lagos, NG',
    setupComplete: true,
    canHostLive: true,
  },
  {
    key: 3,
    username: 'vintagevault.ng',
    email: 'vintagevault.ng@throve.dev',
    name: 'Zainab Vintage',
    bio: 'One-of-one vintage pieces.',
    location: 'Abuja, NG',
    setupComplete: true,
    canHostLive: false,
  },
  {
    key: 4,
    username: 'tolu.styles',
    email: 'tolu.styles@throve.dev',
    name: 'Tolu Styles',
    bio: 'Ankara edits and occasion wear.',
    location: 'Lagos, NG',
    setupComplete: true,
    canHostLive: false,
  },
  {
    key: 5,
    username: 'lagos.preloved',
    email: 'lagos.preloved@throve.dev',
    name: 'Amaka Preloved',
    bio: 'Bags, beauty and accessories.',
    location: 'Lagos, NG',
    setupComplete: true,
    canHostLive: false,
  },
  { key: 6, username: 'funke_b', email: 'funke_b@throve.dev', name: 'Funke Bello', setupComplete: true },
  { key: 7, username: 'chidinma.o', email: 'chidinma.o@throve.dev', name: 'Chidinma Okafor', setupComplete: true },
  { key: 8, username: 'ijeoma.a', email: 'ijeoma.a@throve.dev', name: 'Ijeoma Adeyemi', setupComplete: true },
  { key: 9, username: 'ken.eze', email: 'ken.eze@throve.dev', name: 'Ken Eze', setupComplete: true },
  { key: 10, username: 'femi.k', email: 'femi.k@throve.dev', name: 'Femi Kola', setupComplete: true },
];

export type SeedListing = {
  slug: string;
  seller: string;
  title: string;
  brand: string;
  price: number;
  size: string;
  condition: string;
  department: 'Women' | 'Men' | 'Kids';
  category: string;
  status: 'available' | 'reserved' | 'sold' | 'draft' | 'hidden';
  description: string;
  colour?: string;
  photoCount: number;
  createdAt: string;
  savedBy?: string[];
};

export const SEED_LISTINGS: SeedListing[] = [
  {
    slug: 'l1',
    seller: 'ada.thrifts',
    title: 'Zara Wrap Dress',
    brand: 'Zara',
    price: 18500,
    size: 'M',
    condition: 'Very good',
    department: 'Women',
    category: 'Clothing',
    status: 'available',
    description: 'Floral wrap dress, worn twice, true to size.',
    colour: 'Floral print',
    photoCount: 4,
    createdAt: '2026-08-09',
    savedBy: ['funke_b', 'chidinma.o'],
  },
  {
    slug: 'l2',
    seller: 'sneakerspot.ng',
    title: 'Nike Air Max Trainers',
    brand: 'Nike',
    price: 32000,
    size: 'UK 9',
    condition: 'Good',
    department: 'Men',
    category: 'Shoes',
    status: 'available',
    description: 'Classic Air Max, minor scuffing on the toe.',
    colour: 'White / grey',
    photoCount: 5,
    createdAt: '2026-08-08',
    savedBy: ['ada.thrifts'],
  },
  {
    slug: 'l3',
    seller: 'vintagevault.ng',
    title: 'Vintage Denim Jacket',
    brand: "Levi's",
    price: 14500,
    size: 'L',
    condition: 'Satisfactory',
    department: 'Women',
    category: 'Clothing',
    status: 'reserved',
    description: '90s wash denim jacket, some fading.',
    colour: 'Indigo',
    photoCount: 3,
    createdAt: '2026-07-28',
  },
  {
    slug: 'l4',
    seller: 'tolu.styles',
    title: 'Ankara Two-Piece Set',
    brand: 'Unbranded',
    price: 22000,
    size: 'M',
    condition: 'New without tags',
    department: 'Women',
    category: 'Clothing',
    status: 'available',
    description: 'Custom-tailored Ankara set, never worn.',
    colour: 'Gold / navy',
    photoCount: 4,
    createdAt: '2026-08-06',
  },
  {
    slug: 'l5',
    seller: 'lagos.preloved',
    title: 'Coach Shoulder Bag',
    brand: 'Coach',
    price: 48000,
    size: '—',
    condition: 'Good',
    department: 'Women',
    category: 'Bags',
    status: 'available',
    description: 'Structured leather shoulder bag with dust bag.',
    colour: 'Tan',
    photoCount: 4,
    createdAt: '2026-08-05',
    savedBy: ['ada.thrifts'],
  },
  {
    slug: 'l6',
    seller: 'tolu.styles',
    title: 'Kids Occasion Dress',
    brand: 'Unbranded',
    price: 12000,
    size: '5–6 yrs',
    condition: 'New with tags',
    department: 'Kids',
    category: 'Clothing',
    status: 'available',
    description: 'Party dress for girls, tags attached.',
    colour: 'Blush pink',
    photoCount: 3,
    createdAt: '2026-08-04',
  },
  {
    slug: 'l7',
    seller: 'sneakerspot.ng',
    title: 'Adidas Superstar Sneakers',
    brand: 'Adidas',
    price: 27000,
    size: 'UK 8',
    condition: 'Very good',
    department: 'Men',
    category: 'Shoes',
    status: 'sold',
    description: 'Classic shell-toe, lightly worn.',
    colour: 'White',
    photoCount: 3,
    createdAt: '2026-07-20',
  },
  {
    slug: 'l8',
    seller: 'lagos.preloved',
    title: 'Beaded Clutch Bag',
    brand: 'Unbranded',
    price: 9500,
    size: '—',
    condition: 'Good',
    department: 'Women',
    category: 'Accessories',
    status: 'available',
    description: 'Hand-beaded evening clutch.',
    colour: 'Gold',
    photoCount: 2,
    createdAt: '2026-08-03',
  },
  {
    slug: 'l9',
    seller: 'ada.thrifts',
    title: 'Silk Headwrap Set',
    brand: 'Unbranded',
    price: 6000,
    size: '—',
    condition: 'New with tags',
    department: 'Women',
    category: 'Accessories',
    status: 'available',
    description: 'Set of three silk headwraps, unused.',
    colour: 'Mixed prints',
    photoCount: 3,
    createdAt: '2026-08-02',
    savedBy: ['ken.eze'],
  },
  {
    slug: 'l10',
    seller: 'tolu.styles',
    title: "Men's Ankara Shirt",
    brand: 'Unbranded',
    price: 13500,
    size: 'L',
    condition: 'Very good',
    department: 'Men',
    category: 'Clothing',
    status: 'available',
    description: 'Short-sleeve Ankara print shirt, dry-cleaned.',
    colour: 'Teal print',
    photoCount: 3,
    createdAt: '2026-08-01',
  },
  {
    slug: 'l11',
    seller: 'ada.thrifts',
    title: 'Leather Ankle Boots',
    brand: 'Unbranded',
    price: 21000,
    size: '40',
    condition: 'Good',
    department: 'Women',
    category: 'Shoes',
    status: 'sold',
    description: 'Block-heel ankle boots, light scuffing on the toe.',
    colour: 'Black',
    photoCount: 3,
    createdAt: '2026-07-18',
  },
  {
    slug: 'l12',
    seller: 'tolu.styles',
    title: 'Grooming Kit — Beard & Skin',
    brand: 'Unbranded',
    price: 8500,
    size: '—',
    condition: 'New without tags',
    department: 'Men',
    category: 'Grooming',
    status: 'available',
    description: 'Beard oil, balm and trimmer set, opened once.',
    photoCount: 2,
    createdAt: '2026-07-30',
  },
  {
    slug: 'l13',
    seller: 'ada.thrifts',
    title: 'Fenty Gloss Bomb Duo',
    brand: 'Fenty',
    price: 16000,
    size: '—',
    condition: 'New with tags',
    department: 'Women',
    category: 'Beauty',
    status: 'available',
    description: 'Unopened gloss duo, shade Fussy and Hot Chocolit.',
    colour: 'Nude / cocoa',
    photoCount: 2,
    createdAt: '2026-08-16',
  },
  {
    slug: 'l14',
    seller: 'lagos.preloved',
    title: 'Leather Messenger Bag',
    brand: 'Unbranded',
    price: 24500,
    size: '—',
    condition: 'Very good',
    department: 'Men',
    category: 'Bags',
    status: 'available',
    description: 'Crossbody messenger, fits a 13-inch laptop.',
    colour: 'Cognac',
    photoCount: 4,
    createdAt: '2026-08-15',
  },
  {
    slug: 'l15',
    seller: 'sneakerspot.ng',
    title: 'Kids Canvas Sneakers',
    brand: 'Nike',
    price: 14000,
    size: 'UK 12 kids',
    condition: 'Good',
    department: 'Kids',
    category: 'Shoes',
    status: 'available',
    description: 'Lightly worn court sneakers, original box included.',
    colour: 'Navy',
    photoCount: 3,
    createdAt: '2026-08-14',
  },
  {
    slug: 'l16',
    seller: 'ada.thrifts',
    title: 'Zara Block-Heel Mules',
    brand: 'Zara',
    price: 17500,
    size: '39',
    condition: 'Very good',
    department: 'Women',
    category: 'Shoes',
    status: 'available',
    description: 'Worn twice to events, soles still clean.',
    colour: 'Nude',
    photoCount: 4,
    createdAt: '2026-08-13',
  },
  {
    slug: 'l17',
    seller: 'vintagevault.ng',
    title: 'Beaded Bracelet Set',
    brand: 'Unbranded',
    price: 4500,
    size: '—',
    condition: 'New without tags',
    department: 'Men',
    category: 'Accessories',
    status: 'available',
    description: 'Three-piece wooden bead bracelet set.',
    colour: 'Brown / black',
    photoCount: 2,
    createdAt: '2026-08-12',
  },
  {
    slug: 'l18',
    seller: 'tolu.styles',
    title: 'Kids Mini Backpack',
    brand: 'Unbranded',
    price: 8000,
    size: '—',
    condition: 'Good',
    department: 'Kids',
    category: 'Bags',
    status: 'available',
    description: 'School backpack with chest strap, one scuff on the base.',
    colour: 'Red',
    photoCount: 3,
    createdAt: '2026-08-11',
  },
  {
    slug: 'l19',
    seller: 'ada.thrifts',
    title: 'Kids Hair Bow Pack',
    brand: 'Unbranded',
    price: 3500,
    size: '—',
    condition: 'New with tags',
    department: 'Kids',
    category: 'Accessories',
    status: 'available',
    description: 'Pack of six satin bows, unused.',
    colour: 'Pastel mix',
    photoCount: 1,
    createdAt: '2026-08-10',
  },
];

export const SEED_REVIEWS = [
  { seller: 'ada.thrifts', buyer: 'ijeoma.a', rating: 5, comment: 'Exactly as described, fast shipping.' },
  { seller: 'ada.thrifts', buyer: 'chidinma.o', rating: 4, comment: 'Nice dress, slightly small.' },
  { seller: 'sneakerspot.ng', buyer: 'femi.k', rating: 5, comment: 'Great sneakers, true to size.' },
  { seller: 'vintagevault.ng', buyer: 'ada.thrifts', rating: 3, comment: 'Item had more wear than expected.' },
];

export const SEED_LIVE = [
  {
    key: 1,
    host: 'ada.thrifts',
    title: 'Friday Thrift Pull',
    status: 'live' as const,
    viewers: 128,
    department: 'Women' as const,
    pinnedListing: 'l1',
    featuredListingSlugs: ['l1', 'l9', 'l13'],
    comments: [
      { user: 'funke_b', text: 'Is the wrap dress still available?' },
      { user: 'chidinma.o', text: 'Love this pull' },
      { user: 'ijeoma.a', text: 'Size M please!' },
    ],
  },
  {
    key: 2,
    host: 'sneakerspot.ng',
    title: 'Sneaker Restock',
    status: 'upcoming' as const,
    scheduledAt: 'Tomorrow, 6:00 PM',
    department: 'Men' as const,
    featuredListingSlugs: ['l2', 'l7'],
  },
];

export function usernameToKey(username: string, users: SeedUser[] = SEED_USERS) {
  return users.find((user) => user.username === username)?.key;
}
